name: fake-news
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn=1.6.1
  - matplotlib
  - joblib
  

  # Web frameworks
  - flask
  - flask-cors
  - streamlit

  # Database
  - pymongo
 
